// Language context and translations
import React, { createContext, useContext, useState } from 'react'

const LanguageContext = createContext()

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

const translations = {
  he: {
    // Navigation and Headers
    appTitle: 'אביבי השקעות',
    dashboard: 'לוח בקרה',
    portfolio: 'תיק השקעות',
    orders: 'הזמנות',
    settings: 'הגדרות',
    
    // Dashboard
    totalValue: 'ערך כולל',
    unrealizedPL: 'רווח/הפסד לא ממומש',
    buyingPower: 'כוח קנייה',
    positions: 'עמדות',
    recentActivity: 'פעילות אחרונה',
    portfolioPerformance: 'מעקב ביצועי תיק',
    realTimeData: 'אינטגרציית נתונים בזמן אמת',
    automatedTrading: 'אסטרטגיות מסחר אוטומטיות',
    riskManagement: 'בקרות ניהול סיכונים',
    
    // Portfolio
    refresh: 'רענן',
    accountSummary: 'סיכום חשבון',
    portfolioValue: 'ערך תיק',
    cash: 'מזומן',
    equity: 'הון עצמי',
    positionsCount: 'עמדות',
    noPositions: 'לא נמצאו עמדות. התחל לסחור כדי לראות את התיק שלך כאן.',
    symbol: 'סמל',
    quantity: 'כמות',
    marketValue: 'ערך שוק',
    unrealizedPLPercent: 'רווח/הפסד %',
    
    // Orders
    placeOrder: 'הזמן הזמנה',
    symbolPlaceholder: 'לדוגמה: AAPL',
    quote: 'מחיר',
    orderType: 'סוג הזמנה',
    market: 'שוק',
    limit: 'מוגבל',
    buy: 'קנה',
    sell: 'מכר',
    side: 'צד',
    placingOrder: 'מבצע הזמנה...',
    orderFailed: 'הזמנה נכשלה',
    orderSuccess: 'הזמנה בוצעה בהצלחה!',
    orderInfo: 'מידע הזמנה',
    marketOrders: 'הזמנות שוק: מתבצעות מיד במחיר השוק הנוכחי',
    limitOrders: 'הזמנות מוגבלות: מתבצעות רק במחיר מוגדר או טוב יותר',
    dayOrders: 'הזמנות יומיות: תקפות רק ליום המסחר הנוכחי',
    paperTrading: 'מסחר נייר: כל ההזמנות מדומות (ללא כסף אמיתי)',
    
    // Settings
    paperModeEnabled: 'מצב נייר: מופעל כברירת מחדל. הגדר מפתחות API ב-backend/.env',
    language: 'שפה',
    hebrew: 'עברית',
    english: 'English',
    
    // Charts and Market Data
    marketChart: 'גרף שוק',
    priceChart: 'גרף מחירים',
    update: 'עדכן',
    date: 'תאריך',
    price: 'מחיר',
    volume: 'נפח',
    chartInfo: 'מידע על הגרף',
    chartDescription: 'גרף מחירים פשוט להדגמה. במערכת אמיתית תהיה אינטגרציה עם נתונים היסטוריים.',
    chartNote1: 'נתונים לדוגמה בלבד',
    chartNote2: 'במערכת אמיתית יהיו נתונים אמיתיים',
    chartNote3: 'גרף ASCII פשוט להדגמה',

    // Notifications
    notifications: 'התראות',
    addNotification: 'הוסף התראה',
    notificationPlaceholder: 'הקלד הודעה...',
    add: 'הוסף',
    allNotifications: 'כל ההתראות',
    clearAll: 'נקה הכל',
    noNotifications: 'אין התראות',
    markRead: 'סמן כנקרא',
    notificationTypes: 'סוגי התראות',
    successMessage: 'פעולה הושלמה בהצלחה!',
    warningMessage: 'אזהרה: בדוק את ההגדרות',
    errorMessage: 'שגיאה: משהו השתבש',
    infoMessage: 'מידע: עדכון חשוב',

    // Analytics
    analytics: 'אנליטיקה',
    last7Days: '7 ימים אחרונים',
    last30Days: '30 ימים אחרונים',
    last90Days: '90 ימים אחרונים',
    totalReturn: 'תשואה כוללת',
    maxDrawdown: 'ירידה מקסימלית',
    sharpeRatio: 'יחס שארפ',
    winRate: 'אחוז הצלחה',
    performanceChart: 'גרף ביצועים',
    detailedStats: 'סטטיסטיקות מפורטות',
    tradingStats: 'סטטיסטיקות מסחר',
    riskMetrics: 'מדדי סיכון',
    dailyPerformance: 'ביצועים יומיים',
    value: 'ערך',
    change: 'שינוי',
    changePercent: 'שינוי %',
    totalTrades: 'סה"כ עסקאות',
    avgTradeReturn: 'תשואה ממוצעת לעסקה',
    volatility: 'תנודתיות',
    analyticsInfo: 'מידע על אנליטיקה',
    analyticsDescription: 'אנליטיקה מתקדמת של ביצועי התיק. נתונים לדוגמה בלבד.',
    analyticsNote1: 'נתונים לדוגמה בלבד',
    analyticsNote2: 'במערכת אמיתית יהיו נתונים אמיתיים',
    analyticsNote3: 'מדדי סיכון מחושבים על בסיס היסטוריה',

    // User Preferences
    userPreferences: 'העדפות משתמש',
    languageSettings: 'הגדרות שפה',
    tradingSettings: 'הגדרות מסחר',
    displaySettings: 'הגדרות תצוגה',
    notificationSettings: 'הגדרות התראות',
    preferencesActions: 'פעולות העדפות',
    jerusalem: 'ירושלים',
    newYork: 'ניו יורק',
    london: 'לונדון',
    tokyo: 'טוקיו',
    defaultOrderType: 'סוג הזמנה ברירת מחדל',
    defaultQuantity: 'כמות ברירת מחדל',
    riskTolerance: 'סובלנות סיכון',
    low: 'נמוך',
    medium: 'בינוני',
    high: 'גבוה',
    theme: 'ערכת נושא',
    light: 'בהיר',
    dark: 'כהה',
    auto: 'אוטומטי',
    refreshInterval: 'מרווח רענון',
    enableNotifications: 'הפעל התראות',
    enableSound: 'הפעל צלילים',
    autoRefresh: 'רענון אוטומטי',
    resetPreferences: 'איפוס העדפות',
    exportPreferences: 'ייצא העדפות',
    importPreferences: 'ייבא העדפות',
    currentPreferences: 'העדפות נוכחיות',
    importError: 'שגיאה בייבוא קובץ',

    // Help Guide
    helpGuide: 'מדריך עזרה',
    gettingStarted: 'התחלה',
    tradingGuide: 'מדריך מסחר',
    portfolioGuide: 'מדריך תיק',
    analyticsGuide: 'מדריך אנליטיקה',
    settingsGuide: 'מדריך הגדרות',
    faq: 'שאלות נפוצות',
    welcomeToAvivi: 'ברוכים הבאים לאביבי השקעות',
    welcomeDescription: 'מערכת מסחר אוטונומית מתקדמת עם תמיכה מלאה בעברית.',
    firstSteps: 'צעדים ראשונים',
    step1: 'הגדר את מפתחות API של Alpaca',
    step2: 'הפעל את המערכת במצב נייר',
    step3: 'חקור את הממשק והתכונות',
    step4: 'התחל לסחור בבטחה',
    importantNotes: 'הערות חשובות',
    note1: 'המערכת פועלת במצב נייר כברירת מחדל',
    note2: 'כל ההזמנות מדומות ואין סיכון לכסף אמיתי',
    note3: 'בדוק את הקוד לפני שימוש במסחר אמיתי',
    howToTrade: 'איך לסחור',
    tradingDescription: 'מדריך מפורט למסחר במערכת.',
    orderTypes: 'סוגי הזמנות',
    marketOrder: 'הזמנת שוק',
    marketOrderDesc: 'מתבצעת מיד במחיר השוק הנוכחי',
    limitOrder: 'הזמנה מוגבלת',
    limitOrderDesc: 'מתבצעת רק במחיר מוגדר או טוב יותר',
    tradingSteps: 'שלבי מסחר',
    tradingStep1: 'בחר סמל מניה',
    tradingStep2: 'קבל מחיר עדכני',
    tradingStep3: 'הגדר כמות וצד (קנה/מכר)',
    tradingStep4: 'הזמן את ההזמנה',
    understandingPortfolio: 'הבנת התיק',
    portfolioDescription: 'מדריך להבנת מטריקות התיק.',
    portfolioMetrics: 'מדדי תיק',
    totalValueDesc: 'הערך הכולל של התיק',
    unrealizedPLDesc: 'רווח או הפסד לא ממומש',
    buyingPowerDesc: 'כוח קנייה זמין',
    positionsDesc: 'מספר העמדות הפתוחות',
    understandingAnalytics: 'הבנת אנליטיקה',
    keyMetrics: 'מדדי מפתח',
    totalReturnDesc: 'התשואה הכוללת של התיק',
    maxDrawdownDesc: 'הירידה המקסימלית מהשיא',
    sharpeRatioDesc: 'יחס שארפ למדידת סיכון-תשואה',
    winRateDesc: 'אחוז העסקאות הרווחיות',
    customizingSettings: 'התאמת הגדרות',
    settingsDescription: 'מדריך להתאמת הגדרות המערכת.',
    preferenceCategories: 'קטגוריות העדפות',
    languageSettingsDesc: 'הגדרות שפה וזמן',
    tradingSettingsDesc: 'הגדרות מסחר ברירת מחדל',
    displaySettingsDesc: 'הגדרות תצוגה ועיצוב',
    notificationSettingsDesc: 'הגדרות התראות וצלילים',
    frequentlyAskedQuestions: 'שאלות נפוצות',
    faq1: 'האם המערכת בטוחה לשימוש?',
    faq1Answer: 'כן, המערכת פועלת במצב נייר כברירת מחדל ואין סיכון לכסף אמיתי.',
    faq2: 'איך אני עובר למסחר אמיתי?',
    faq2Answer: 'שנה את PAPER_MODE ל-false בקובץ .env לאחר בדיקה מקיפה.',
    faq3: 'איך אני מוסיף אסטרטגיות חדשות?',
    faq3Answer: 'השתמש בקובץ example_momentum_strategy.py כדוגמה לפיתוח אסטרטגיות.',
    faq4: 'האם המערכת תומכת בעברית?',
    faq4Answer: 'כן, המערכת תומכת מלאה בעברית עם RTL.',
    faq5: 'איך אני מקבל תמיכה?',
    faq5Answer: 'השתמש במדריך העזרה או בדוק את התיעוד.',
    quickActions: 'פעולות מהירות',
    startTrading: 'התחל מסחר',
    viewFAQ: 'צפה בשאלות נפוצות',
    customizeSettings: 'התאם הגדרות',

    // Advanced Charts
    advancedCharts: 'גרפים מתקדמים',
    chartType: 'סוג גרף',
    timeframe: 'תקופת זמן',
    chartTitle: 'גרף',
    candlestick: 'נרות יפניים',
    lineChart: 'גרף קו',
    rsi: 'RSI',
    macd: 'MACD',
    candlestickDesc: 'גרף נרות יפניים עם מחירי פתיחה, סגירה, גבוה ונמוך',
    lineChartDesc: 'גרף קו פשוט של מחירי סגירה',
    volumeDesc: 'גרף נפח מסחר',
    rsiDesc: 'מדד RSI לזיהוי מצבי קנייה/מכירה',
    macdDesc: 'מדד MACD לזיהוי מגמות',

    // Real Time Data
    realTimeData: 'נתוני שוק בזמן אמת',
    marketStatus: 'סטטוס שוק',
    marketOpen: 'שוק פתוח',
    marketClosed: 'שוק סגור',
    lastUpdate: 'עדכון אחרון',
    never: 'מעולם לא',
    totalSymbols: 'סה"כ סמלים',
    refreshRate: 'קצב רענון',
    changePercent: 'שינוי %',
    marketCap: 'שווי שוק',
    pe: 'P/E',
    dividend: 'דיבידנד',
    marketOverview: 'סקירת שוק',
    topGainers: 'העולים ביותר',
    topLosers: 'היורדים ביותר',
    mostActive: 'הפעילים ביותר',
    dataInfo: 'מידע על נתונים',
    dataDescription: 'נתוני שוק בזמן אמת עם עדכונים אוטומטיים.',
    dataNote1: 'נתונים לדוגמה בלבד',
    dataNote2: 'במערכת אמיתית יהיו נתונים אמיתיים',
    dataNote3: 'עדכונים אוטומטיים כל 30 שניות',

    // Trading Strategies
    tradingStrategies: 'אסטרטגיות מסחר',
    totalStrategies: 'סה"כ אסטרטגיות',
    activeStrategies: 'אסטרטגיות פעילות',
    avgReturn: 'תשואה ממוצעת',
    avgSharpe: 'שארפ ממוצע',
    momentumStrategy: 'אסטרטגיית מומנטום',
    momentumStrategyDesc: 'מזהה מגמות ומסחר בכיוון התנועה',
    meanReversionStrategy: 'אסטרטגיית חזרה לממוצע',
    meanReversionStrategyDesc: 'מסחר נגד מגמות קיצוניות',
    breakoutStrategy: 'אסטרטגיית פריצה',
    breakoutStrategyDesc: 'מזהה פריצות מפלסי תמיכה/התנגדות',
    arbitrageStrategy: 'אסטרטגיית ארביטראז',
    arbitrageStrategyDesc: 'מנצל פערי מחירים בין שווקים',
    expectedReturn: 'תשואה צפויה',
    strategyParameters: 'פרמטרי אסטרטגיה',
    lookbackPeriod: 'תקופת מבט אחורה',
    threshold: 'סף',
    stopLoss: 'סטופ לוס',
    takeProfit: 'טייק פרופיט',
    activate: 'הפעל',
    deactivate: 'השבת',
    strategyActive: 'אסטרטגיה פעילה',
    strategyInactive: 'אסטרטגיה לא פעילה',
    strategyInfo: 'מידע על אסטרטגיות',
    strategyDescription: 'אסטרטגיות מסחר אוטומטיות מתקדמות.',
    strategyNote1: 'אסטרטגיות לדוגמה בלבד',
    strategyNote2: 'במערכת אמיתית יהיו אסטרטגיות אמיתיות',
    strategyNote3: 'בדוק את הקוד לפני שימוש במסחר אמיתי',

    // Risk Management
    riskManagement: 'ניהול סיכונים',
    riskSettings: 'הגדרות סיכון',
    maxPositionSize: 'גודל עמדה מקסימלי',
    maxPortfolioRisk: 'סיכון תיק מקסימלי',
    stopLossPercentage: 'אחוז סטופ לוס',
    takeProfitPercentage: 'אחוז טייק פרופיט',
    positionRisks: 'סיכוני עמדות',
    correlationMatrix: 'מטריצת קורלציה',
    stressTestResults: 'תוצאות בדיקת לחץ',
    marketCrash: 'התרסקות שוק',
    recession: 'מיתון',
    volatilitySpike: 'עלייה בתנודתיות',
    sectorRotation: 'רוטציה סקטוריאלית',
    interestRateHike: 'עליית ריבית',
    probability: 'הסתברות',
    impact: 'השפעה',
    riskAlerts: 'התראות סיכון',
    highCorrelationAlert: 'קורלציה גבוהה בין עמדות',
    volatilityIncreaseAlert: 'עלייה בתנודתיות השוק',
    drawdownLimitAlert: 'הגעה לגבול ירידה מקסימלית',
    high: 'גבוה',
    medium: 'בינוני',
    low: 'נמוך',
    riskInfo: 'מידע על ניהול סיכונים',
    riskDescription: 'ניהול סיכונים מתקדם עם בקרות אוטומטיות.',
    riskNote1: 'בקרות סיכון אוטומטיות',
    riskNote2: 'התראות בזמן אמת',
    riskNote3: 'בדיקות לחץ מתקדמות',

    // Portfolio Optimization
    portfolioOptimization: 'אופטימיזציה של תיק',
    optimizationSettings: 'הגדרות אופטימיזציה',
    targetReturn: 'תשואה יעד',
    maxRisk: 'סיכון מקסימלי',
    rebalanceFrequency: 'תדירות איזון מחדש',
    daily: 'יומי',
    weekly: 'שבועי',
    monthly: 'חודשי',
    quarterly: 'רבעוני',
    transactionCost: 'עלות עסקה',
    taxRate: 'שיעור מס',
    currentPortfolio: 'תיק נוכחי',
    weight: 'משקל',
    value: 'ערך',
    change: 'שינוי',
    optimizedPortfolio: 'תיק מותאם',
    optimizationDetails: 'פרטי אופטימיזציה',
    diversificationRatio: 'יחס פיזור',
    concentrationRisk: 'סיכון ריכוז',
    rebalanceCost: 'עלות איזון מחדש',
    taxImpact: 'השפעת מס',
    improvement: 'שיפור',
    runOptimization: 'הפעל אופטימיזציה',
    optimizing: 'מתאים...',
    optimizationInfo: 'מידע על אופטימיזציה',
    optimizationDescription: 'אופטימיזציה מתקדמת של תיק השקעות.',
    optimizationNote1: 'אלגוריתמי אופטימיזציה מתקדמים',
    optimizationNote2: 'בחינת עלויות עסקה ומס',
    optimizationNote3: 'התאמה למטרות השקעה',

    // Advanced Reporting
    advancedReporting: 'דוחות מתקדמים',
    generateReport: 'צור דוח',
    reportType: 'סוג דוח',
    performanceReport: 'דוח ביצועים',
    riskReport: 'דוח סיכונים',
    taxReport: 'דוח מס',
    complianceReport: 'דוח ציות',
    customReport: 'דוח מותאם אישית',
    timeRange: 'טווח זמן',
    includeCharts: 'כלול גרפים',
    includeDetails: 'כלול פרטים',
    format: 'פורמט',
    schedule: 'תזמון',
    generating: 'יוצר...',
    reportPreview: 'תצוגה מקדימה של דוח',
    performanceMetrics: 'מדדי ביצועים',
    totalReturn: 'תשואה כוללת',
    annualizedReturn: 'תשואה שנתית',
    winRate: 'אחוז הצלחה',
    profitFactor: 'גורם רווח',
    trades: 'עסקאות',
    avgTrade: 'עסקה ממוצעת',
    bestTrade: 'עסקה טובה ביותר',
    worstTrade: 'עסקה גרועה ביותר',
    riskMetrics: 'מדדי סיכון',
    taxInformation: 'מידע מס',
    realizedGains: 'רווחים ממומשים',
    realizedLosses: 'הפסדים ממומשים',
    netGains: 'רווחים נטו',
    taxOwed: 'מס חובה',
    reportsHistory: 'היסטוריית דוחות',
    name: 'שם',
    type: 'סוג',
    date: 'תאריך',
    status: 'סטטוס',
    size: 'גודל',
    pages: 'עמודים',
    actions: 'פעולות',
    download: 'הורד',
    reportingInfo: 'מידע על דוחות',
    reportingDescription: 'דוחות מתקדמים עם ניתוח מפורט.',
    reportingNote1: 'דוחות מותאמים אישית',
    reportingNote2: 'ניתוח מפורט של ביצועים',
    reportingNote3: 'ייצוא למגוון פורמטים',

    // AI Trading Assistant
    aiTradingAssistant: 'עוזר AI למסחר',
    assistantMode: 'מצב עוזר',
    general: 'כללי',
    trading: 'מסחר',
    analysis: 'ניתוח',
    risk: 'סיכון',
    tax: 'מס',
    quickActions: 'פעולות מהירות',
    analyzePortfolio: 'נתח תיק',
    marketOutlook: 'תחזית שוק',
    riskAssessment: 'הערכת סיכון',
    tradingStrategy: 'אסטרטגיית מסחר',
    taxOptimization: 'אופטימיזציה מס',
    complianceCheck: 'בדיקת ציות',
    chatWithAssistant: 'שוחח עם העוזר',
    typeYourMessage: 'הקלד את ההודעה שלך',
    send: 'שלח',
    aiCapabilities: 'יכולות AI',
    portfolioAnalysis: 'ניתוח תיק',
    portfolioAnalysisDesc: 'ניתוח מתקדם של תיק השקעות',
    marketInsights: 'תובנות שוק',
    marketInsightsDesc: 'תחזיות ותובנות שוק',
    riskAssessmentDesc: 'הערכת סיכונים מתקדמת',
    taxOptimizationDesc: 'אופטימיזציה מס מתקדמת',
    aiInfo: 'מידע על AI',
    aiDescription: 'עוזר AI מתקדם למסחר וניתוח.',
    aiNote1: 'ניתוח מתקדם של נתונים',
    aiNote2: 'המלצות מותאמות אישית',
    aiNote3: 'תמיכה 24/7',
    aiWelcomeMessage: 'שלום! אני העוזר AI שלך למסחר. איך אוכל לעזור לך היום?',
    aiTradingAdvice: 'אני ממליץ לך לבדוק את הניתוח הטכני והפונדמנטלי לפני ביצוע עסקה. זכור לנהל סיכונים ולגוון את התיק.',
    aiPortfolioAdvice: 'התיק שלך נראה מגוון היטב. אני ממליץ לבדוק את האיזון בין סיכון לתשואה ולעדכן את ההקצאה בהתאם למטרות שלך.',
    aiRiskAdvice: 'ניהול סיכונים הוא המפתח להצלחה. אני ממליץ להשתמש בסטופ לוס, לגוון את התיק ולעקוב אחר מדדי סיכון.',
    aiMarketAnalysis: 'השוק מראה סימני תנודתיות. אני ממליץ לבדוק את המדדים הטכניים ולעקוב אחר חדשות כלכליות.',
    aiTechnicalAnalysis: 'הניתוח הטכני מראה סימנים מעורבים. אני ממליץ לבדוק את ה-RSI, MACD וממוצעים נעים.',
    aiGeneralHelp: 'אני כאן לעזור לך עם כל שאלה בנושא מסחר, השקעות וניהול תיק. מה תרצה לדעת?',
    aiDefaultResponse: 'אני מבין את השאלה שלך. אני כאן לעזור לך עם כל נושא הקשור למסחר והשקעות. איך אוכל לעזור לך יותר?',
    analyzeMyPortfolio: 'נתח את התיק שלי',
    whatIsMarketOutlook: 'מה התחזית לשוק?',
    assessMyRisk: 'הערך את הסיכון שלי',
    suggestTradingStrategy: 'הצע אסטרטגיית מסחר',
    optimizeMyTaxes: 'אופטימיזציה מס שלי',
    checkCompliance: 'בדוק ציות',

    // Social Trading
    socialTrading: 'מסחר חברתי',
    leaderboard: 'לוח מובילים',
    rank: 'דירוג',
    trader: 'סוחר',
    return: 'תשואה',
    followers: 'עוקבים',
    following: 'עוקב',
    topTraders: 'סוחרים מובילים',
    socialFeed: 'פיד חברתי',
    follow: 'עקוב',
    unfollow: 'בטל עקיבה',
    justNow: 'עכשיו',
    openedPosition: 'פתח עמדה',
    sharedAnalysis: 'שיתף ניתוח',
    closedPosition: 'סגר עמדה',
    profit: 'רווח',
    socialTradingInfo: 'מידע על מסחר חברתי',
    socialTradingDescription: 'מסחר חברתי עם סוחרים מובילים.',
    socialTradingNote1: 'עקוב אחר סוחרים מובילים',
    socialTradingNote2: 'שתף אסטרטגיות מסחר',
    socialTradingNote3: 'למד מסוחרים מנוסים',

    // Advanced Security
    advancedSecurity: 'אבטחה מתקדמת',
    securityScore: 'ציון אבטחה',
    excellent: 'מעולה',
    good: 'טוב',
    fair: 'בינוני',
    poor: 'חלש',
    twoFactorAuth: 'אימות דו-שלבי',
    biometricAuth: 'אימות ביומטרי',
    activeSessions: 'סשנים פעילים',
    securitySettings: 'הגדרות אבטחה',
    twoFactorAuthDesc: 'אימות נוסף עם קוד SMS או אפליקציה',
    biometricAuthDesc: 'אימות עם טביעת אצבע או זיהוי פנים',
    sessionTimeout: 'פסק זמן סשן',
    maxLoginAttempts: 'מקסימום ניסיונות התחברות',
    passwordExpiry: 'תפוגת סיסמה',
    autoLogout: 'התנתקות אוטומטית',
    autoLogoutDesc: 'התנתקות אוטומטית לאחר זמן ללא פעילות',
    securityEvents: 'אירועי אבטחה',
    successfulLogin: 'התחברות מוצלחת',
    failedLoginAttempt: 'ניסיון התחברות כושל',
    passwordChanged: 'סיסמה שונתה',
    suspiciousActivityDetected: 'פעילות חשודה זוהתה',
    loginHistory: 'היסטוריית התחברות',
    timestamp: 'זמן',
    ip: 'כתובת IP',
    location: 'מיקום',
    device: 'מכשיר',
    status: 'סטטוס',
    securityRecommendations: 'המלצות אבטחה',
    enableTwoFactorAuth: 'הפעל אימות דו-שלבי',
    enableTwoFactorAuthDesc: 'מומלץ להפעיל אימות דו-שלבי להגנה נוספת',
    shortenPasswordExpiry: 'קצר את תפוגת הסיסמה',
    shortenPasswordExpiryDesc: 'מומלץ לקצר את תפוגת הסיסמה ל-30-90 יום',
    shortenSessionTimeout: 'קצר את פסק זמן הסשן',
    shortenSessionTimeoutDesc: 'מומלץ לקצר את פסק זמן הסשן ל-30 דקות',
    securityInfo: 'מידע על אבטחה',
    securityDescription: 'אבטחה מתקדמת עם בקרות מקצועיות.',
    securityNote1: 'אימות דו-שלבי',
    securityNote2: 'ניטור פעילות חשודה',
    securityNote3: 'התנתקות אוטומטית',

    // Common
    loading: 'טוען...',
    error: 'שגיאה',
    retry: 'נסה שוב',
    success: 'הצלחה',
    warning: 'אזהרה',
    info: 'מידע',
    cancel: 'ביטול',
    save: 'שמור',
    edit: 'ערוך',
    delete: 'מחק',
    confirm: 'אשר',
    close: 'סגור'
  },
  en: {
    // Navigation and Headers
    appTitle: 'Avivi Invest',
    dashboard: 'Dashboard',
    portfolio: 'Portfolio',
    orders: 'Orders',
    settings: 'Settings',
    
    // Dashboard
    totalValue: 'Total Value',
    unrealizedPL: 'Unrealized P&L',
    buyingPower: 'Buying Power',
    positions: 'Positions',
    recentActivity: 'Recent Activity',
    portfolioPerformance: 'Portfolio performance tracking',
    realTimeData: 'Real-time market data integration',
    automatedTrading: 'Automated trading strategies',
    riskManagement: 'Risk management controls',
    
    // Portfolio
    refresh: 'Refresh',
    accountSummary: 'Account Summary',
    portfolioValue: 'Portfolio Value',
    cash: 'Cash',
    equity: 'Equity',
    positionsCount: 'Positions',
    noPositions: 'No positions found. Start trading to see your portfolio here.',
    symbol: 'Symbol',
    quantity: 'Quantity',
    marketValue: 'Market Value',
    unrealizedPLPercent: 'P&L %',
    
    // Orders
    placeOrder: 'Place Order',
    symbolPlaceholder: 'e.g., AAPL',
    quote: 'Quote',
    orderType: 'Order Type',
    market: 'Market',
    limit: 'Limit',
    buy: 'Buy',
    sell: 'Sell',
    side: 'Side',
    placingOrder: 'Placing Order...',
    orderFailed: 'Order Failed',
    orderSuccess: 'Order Placed Successfully!',
    orderInfo: 'Order Information',
    marketOrders: 'Market Orders: Execute immediately at current market price',
    limitOrders: 'Limit Orders: Execute only at specified price or better',
    dayOrders: 'Day Orders: Valid only for the current trading day',
    paperTrading: 'Paper Trading: All orders are simulated (no real money)',
    
    // Settings
    paperModeEnabled: 'Paper Mode: enabled by default. Configure API keys in backend/.env',
    language: 'Language',
    hebrew: 'עברית',
    english: 'English',
    
    // Charts and Market Data
    marketChart: 'Market Chart',
    priceChart: 'Price Chart',
    update: 'Update',
    date: 'Date',
    price: 'Price',
    volume: 'Volume',
    chartInfo: 'Chart Information',
    chartDescription: 'Simple price chart for demonstration. In a real system there would be integration with historical data.',
    chartNote1: 'Demo data only',
    chartNote2: 'Real system would have real data',
    chartNote3: 'Simple ASCII chart for demonstration',

    // Notifications
    notifications: 'Notifications',
    addNotification: 'Add Notification',
    notificationPlaceholder: 'Type a message...',
    add: 'Add',
    allNotifications: 'All Notifications',
    clearAll: 'Clear All',
    noNotifications: 'No notifications',
    markRead: 'Mark Read',
    notificationTypes: 'Notification Types',
    successMessage: 'Operation completed successfully!',
    warningMessage: 'Warning: Check your settings',
    errorMessage: 'Error: Something went wrong',
    infoMessage: 'Info: Important update',

    // Analytics
    analytics: 'Analytics',
    last7Days: 'Last 7 Days',
    last30Days: 'Last 30 Days',
    last90Days: 'Last 90 Days',
    totalReturn: 'Total Return',
    maxDrawdown: 'Max Drawdown',
    sharpeRatio: 'Sharpe Ratio',
    winRate: 'Win Rate',
    performanceChart: 'Performance Chart',
    detailedStats: 'Detailed Statistics',
    tradingStats: 'Trading Statistics',
    riskMetrics: 'Risk Metrics',
    dailyPerformance: 'Daily Performance',
    value: 'Value',
    change: 'Change',
    changePercent: 'Change %',
    totalTrades: 'Total Trades',
    avgTradeReturn: 'Average Trade Return',
    volatility: 'Volatility',
    analyticsInfo: 'Analytics Information',
    analyticsDescription: 'Advanced portfolio performance analytics. Demo data only.',
    analyticsNote1: 'Demo data only',
    analyticsNote2: 'Real system would have real data',
    analyticsNote3: 'Risk metrics calculated based on history',

    // User Preferences
    userPreferences: 'User Preferences',
    languageSettings: 'Language Settings',
    tradingSettings: 'Trading Settings',
    displaySettings: 'Display Settings',
    notificationSettings: 'Notification Settings',
    preferencesActions: 'Preference Actions',
    jerusalem: 'Jerusalem',
    newYork: 'New York',
    london: 'London',
    tokyo: 'Tokyo',
    defaultOrderType: 'Default Order Type',
    defaultQuantity: 'Default Quantity',
    riskTolerance: 'Risk Tolerance',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    auto: 'Auto',
    refreshInterval: 'Refresh Interval',
    enableNotifications: 'Enable Notifications',
    enableSound: 'Enable Sound',
    autoRefresh: 'Auto Refresh',
    resetPreferences: 'Reset Preferences',
    exportPreferences: 'Export Preferences',
    importPreferences: 'Import Preferences',
    currentPreferences: 'Current Preferences',
    importError: 'Error importing file',

    // Help Guide
    helpGuide: 'Help Guide',
    gettingStarted: 'Getting Started',
    tradingGuide: 'Trading Guide',
    portfolioGuide: 'Portfolio Guide',
    analyticsGuide: 'Analytics Guide',
    settingsGuide: 'Settings Guide',
    faq: 'FAQ',
    welcomeToAvivi: 'Welcome to Avivi Invest',
    welcomeDescription: 'Advanced autonomous trading system with full Hebrew support.',
    firstSteps: 'First Steps',
    step1: 'Configure Alpaca API keys',
    step2: 'Run the system in paper mode',
    step3: 'Explore the interface and features',
    step4: 'Start trading safely',
    importantNotes: 'Important Notes',
    note1: 'System runs in paper mode by default',
    note2: 'All orders are simulated with no real money risk',
    note3: 'Review the code before using for live trading',
    howToTrade: 'How to Trade',
    tradingDescription: 'Detailed guide for trading in the system.',
    orderTypes: 'Order Types',
    marketOrder: 'Market Order',
    marketOrderDesc: 'Executes immediately at current market price',
    limitOrder: 'Limit Order',
    limitOrderDesc: 'Executes only at specified price or better',
    tradingSteps: 'Trading Steps',
    tradingStep1: 'Select a stock symbol',
    tradingStep2: 'Get current price',
    tradingStep3: 'Set quantity and side (buy/sell)',
    tradingStep4: 'Place the order',
    understandingPortfolio: 'Understanding Portfolio',
    portfolioDescription: 'Guide to understanding portfolio metrics.',
    portfolioMetrics: 'Portfolio Metrics',
    totalValueDesc: 'Total value of the portfolio',
    unrealizedPLDesc: 'Unrealized profit or loss',
    buyingPowerDesc: 'Available buying power',
    positionsDesc: 'Number of open positions',
    understandingAnalytics: 'Understanding Analytics',
    keyMetrics: 'Key Metrics',
    totalReturnDesc: 'Total return of the portfolio',
    maxDrawdownDesc: 'Maximum decline from peak',
    sharpeRatioDesc: 'Sharpe ratio for risk-return measurement',
    winRateDesc: 'Percentage of profitable trades',
    customizingSettings: 'Customizing Settings',
    settingsDescription: 'Guide to customizing system settings.',
    preferenceCategories: 'Preference Categories',
    languageSettingsDesc: 'Language and time settings',
    tradingSettingsDesc: 'Default trading settings',
    displaySettingsDesc: 'Display and design settings',
    notificationSettingsDesc: 'Notification and sound settings',
    frequentlyAskedQuestions: 'Frequently Asked Questions',
    faq1: 'Is the system safe to use?',
    faq1Answer: 'Yes, the system runs in paper mode by default with no real money risk.',
    faq2: 'How do I switch to live trading?',
    faq2Answer: 'Change PAPER_MODE to false in .env file after thorough testing.',
    faq3: 'How do I add new strategies?',
    faq3Answer: 'Use example_momentum_strategy.py as a template for strategy development.',
    faq4: 'Does the system support Hebrew?',
    faq4Answer: 'Yes, the system has full Hebrew support with RTL.',
    faq5: 'How do I get support?',
    faq5Answer: 'Use the help guide or check the documentation.',
    quickActions: 'Quick Actions',
    startTrading: 'Start Trading',
    viewFAQ: 'View FAQ',
    customizeSettings: 'Customize Settings',

    // Advanced Charts
    advancedCharts: 'Advanced Charts',
    chartType: 'Chart Type',
    timeframe: 'Timeframe',
    chartTitle: 'Chart',
    candlestick: 'Candlestick',
    lineChart: 'Line Chart',
    rsi: 'RSI',
    macd: 'MACD',
    candlestickDesc: 'Candlestick chart with open, close, high, and low prices',
    lineChartDesc: 'Simple line chart of closing prices',
    volumeDesc: 'Trading volume chart',
    rsiDesc: 'RSI indicator for buy/sell signals',
    macdDesc: 'MACD indicator for trend identification',

    // Real Time Data
    realTimeData: 'Real-Time Market Data',
    marketStatus: 'Market Status',
    marketOpen: 'Market Open',
    marketClosed: 'Market Closed',
    lastUpdate: 'Last Update',
    never: 'Never',
    totalSymbols: 'Total Symbols',
    refreshRate: 'Refresh Rate',
    changePercent: 'Change %',
    marketCap: 'Market Cap',
    pe: 'P/E',
    dividend: 'Dividend',
    marketOverview: 'Market Overview',
    topGainers: 'Top Gainers',
    topLosers: 'Top Losers',
    mostActive: 'Most Active',
    dataInfo: 'Data Information',
    dataDescription: 'Real-time market data with automatic updates.',
    dataNote1: 'Demo data only',
    dataNote2: 'Real system would have real data',
    dataNote3: 'Automatic updates every 30 seconds',

    // Trading Strategies
    tradingStrategies: 'Trading Strategies',
    totalStrategies: 'Total Strategies',
    activeStrategies: 'Active Strategies',
    avgReturn: 'Average Return',
    avgSharpe: 'Average Sharpe',
    momentumStrategy: 'Momentum Strategy',
    momentumStrategyDesc: 'Identifies trends and trades in the direction of movement',
    meanReversionStrategy: 'Mean Reversion Strategy',
    meanReversionStrategyDesc: 'Trades against extreme trends',
    breakoutStrategy: 'Breakout Strategy',
    breakoutStrategyDesc: 'Identifies breakouts from support/resistance levels',
    arbitrageStrategy: 'Arbitrage Strategy',
    arbitrageStrategyDesc: 'Exploits price differences between markets',
    expectedReturn: 'Expected Return',
    strategyParameters: 'Strategy Parameters',
    lookbackPeriod: 'Lookback Period',
    threshold: 'Threshold',
    stopLoss: 'Stop Loss',
    takeProfit: 'Take Profit',
    activate: 'Activate',
    deactivate: 'Deactivate',
    strategyActive: 'Strategy Active',
    strategyInactive: 'Strategy Inactive',
    strategyInfo: 'Strategy Information',
    strategyDescription: 'Advanced automated trading strategies.',
    strategyNote1: 'Demo strategies only',
    strategyNote2: 'Real system would have real strategies',
    strategyNote3: 'Review code before using for live trading',

    // Risk Management
    riskManagement: 'Risk Management',
    riskSettings: 'Risk Settings',
    maxPositionSize: 'Max Position Size',
    maxPortfolioRisk: 'Max Portfolio Risk',
    stopLossPercentage: 'Stop Loss Percentage',
    takeProfitPercentage: 'Take Profit Percentage',
    positionRisks: 'Position Risks',
    correlationMatrix: 'Correlation Matrix',
    stressTestResults: 'Stress Test Results',
    marketCrash: 'Market Crash',
    recession: 'Recession',
    volatilitySpike: 'Volatility Spike',
    sectorRotation: 'Sector Rotation',
    interestRateHike: 'Interest Rate Hike',
    probability: 'Probability',
    impact: 'Impact',
    riskAlerts: 'Risk Alerts',
    highCorrelationAlert: 'High correlation between positions',
    volatilityIncreaseAlert: 'Market volatility increase',
    drawdownLimitAlert: 'Reached maximum drawdown limit',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    riskInfo: 'Risk Management Information',
    riskDescription: 'Advanced risk management with automatic controls.',
    riskNote1: 'Automatic risk controls',
    riskNote2: 'Real-time alerts',
    riskNote3: 'Advanced stress testing',

    // Portfolio Optimization
    portfolioOptimization: 'Portfolio Optimization',
    optimizationSettings: 'Optimization Settings',
    targetReturn: 'Target Return',
    maxRisk: 'Max Risk',
    rebalanceFrequency: 'Rebalance Frequency',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    quarterly: 'Quarterly',
    transactionCost: 'Transaction Cost',
    taxRate: 'Tax Rate',
    currentPortfolio: 'Current Portfolio',
    weight: 'Weight',
    value: 'Value',
    change: 'Change',
    optimizedPortfolio: 'Optimized Portfolio',
    optimizationDetails: 'Optimization Details',
    diversificationRatio: 'Diversification Ratio',
    concentrationRisk: 'Concentration Risk',
    rebalanceCost: 'Rebalance Cost',
    taxImpact: 'Tax Impact',
    improvement: 'Improvement',
    runOptimization: 'Run Optimization',
    optimizing: 'Optimizing...',
    optimizationInfo: 'Optimization Information',
    optimizationDescription: 'Advanced portfolio optimization.',
    optimizationNote1: 'Advanced optimization algorithms',
    optimizationNote2: 'Transaction cost and tax consideration',
    optimizationNote3: 'Alignment with investment goals',

    // Advanced Reporting
    advancedReporting: 'Advanced Reporting',
    generateReport: 'Generate Report',
    reportType: 'Report Type',
    performanceReport: 'Performance Report',
    riskReport: 'Risk Report',
    taxReport: 'Tax Report',
    complianceReport: 'Compliance Report',
    customReport: 'Custom Report',
    timeRange: 'Time Range',
    includeCharts: 'Include Charts',
    includeDetails: 'Include Details',
    format: 'Format',
    schedule: 'Schedule',
    generating: 'Generating...',
    reportPreview: 'Report Preview',
    performanceMetrics: 'Performance Metrics',
    totalReturn: 'Total Return',
    annualizedReturn: 'Annualized Return',
    winRate: 'Win Rate',
    profitFactor: 'Profit Factor',
    trades: 'Trades',
    avgTrade: 'Avg Trade',
    bestTrade: 'Best Trade',
    worstTrade: 'Worst Trade',
    riskMetrics: 'Risk Metrics',
    taxInformation: 'Tax Information',
    realizedGains: 'Realized Gains',
    realizedLosses: 'Realized Losses',
    netGains: 'Net Gains',
    taxOwed: 'Tax Owed',
    reportsHistory: 'Reports History',
    name: 'Name',
    type: 'Type',
    date: 'Date',
    status: 'Status',
    size: 'Size',
    pages: 'Pages',
    actions: 'Actions',
    download: 'Download',
    reportingInfo: 'Reporting Information',
    reportingDescription: 'Advanced reporting with detailed analysis.',
    reportingNote1: 'Customizable reports',
    reportingNote2: 'Detailed performance analysis',
    reportingNote3: 'Export to multiple formats',

    // AI Trading Assistant
    aiTradingAssistant: 'AI Trading Assistant',
    assistantMode: 'Assistant Mode',
    general: 'General',
    trading: 'Trading',
    analysis: 'Analysis',
    risk: 'Risk',
    tax: 'Tax',
    quickActions: 'Quick Actions',
    analyzePortfolio: 'Analyze Portfolio',
    marketOutlook: 'Market Outlook',
    riskAssessment: 'Risk Assessment',
    tradingStrategy: 'Trading Strategy',
    taxOptimization: 'Tax Optimization',
    complianceCheck: 'Compliance Check',
    chatWithAssistant: 'Chat with Assistant',
    typeYourMessage: 'Type your message...',
    send: 'Send',
    aiCapabilities: 'AI Capabilities',
    portfolioAnalysis: 'Portfolio Analysis',
    portfolioAnalysisDesc: 'Advanced portfolio analysis',
    marketInsights: 'Market Insights',
    marketInsightsDesc: 'Market forecasts and insights',
    riskAssessmentDesc: 'Advanced risk assessment',
    taxOptimizationDesc: 'Advanced tax optimization',
    aiInfo: 'AI Information',
    aiDescription: 'Advanced AI assistant for trading and analysis.',
    aiNote1: 'Advanced data analysis',
    aiNote2: 'Personalized recommendations',
    aiNote3: '24/7 support',
    aiWelcomeMessage: 'Hello! I\'m your AI trading assistant. How can I help you today?',
    aiTradingAdvice: 'I recommend checking technical and fundamental analysis before making trades. Remember to manage risk and diversify your portfolio.',
    aiPortfolioAdvice: 'Your portfolio looks well diversified. I recommend checking the risk-return balance and updating allocation according to your goals.',
    aiRiskAdvice: 'Risk management is key to success. I recommend using stop losses, diversifying your portfolio, and monitoring risk metrics.',
    aiMarketAnalysis: 'The market shows signs of volatility. I recommend checking technical indicators and following economic news.',
    aiTechnicalAnalysis: 'Technical analysis shows mixed signals. I recommend checking RSI, MACD, and moving averages.',
    aiGeneralHelp: 'I\'m here to help you with any questions about trading, investing, and portfolio management. What would you like to know?',
    aiDefaultResponse: 'I understand your question. I\'m here to help you with any trading and investment related topics. How can I help you further?',
    analyzeMyPortfolio: 'Analyze my portfolio',
    whatIsMarketOutlook: 'What is the market outlook?',
    assessMyRisk: 'Assess my risk',
    suggestTradingStrategy: 'Suggest trading strategy',
    optimizeMyTaxes: 'Optimize my taxes',
    checkCompliance: 'Check compliance',

    // Social Trading
    socialTrading: 'Social Trading',
    leaderboard: 'Leaderboard',
    rank: 'Rank',
    trader: 'Trader',
    return: 'Return',
    followers: 'Followers',
    following: 'Following',
    topTraders: 'Top Traders',
    socialFeed: 'Social Feed',
    follow: 'Follow',
    unfollow: 'Unfollow',
    justNow: 'Just now',
    openedPosition: 'Opened Position',
    sharedAnalysis: 'Shared Analysis',
    closedPosition: 'Closed Position',
    profit: 'Profit',
    socialTradingInfo: 'Social Trading Information',
    socialTradingDescription: 'Social trading with top traders.',
    socialTradingNote1: 'Follow top traders',
    socialTradingNote2: 'Share trading strategies',
    socialTradingNote3: 'Learn from experienced traders',

    // Advanced Security
    advancedSecurity: 'Advanced Security',
    securityScore: 'Security Score',
    excellent: 'Excellent',
    good: 'Good',
    fair: 'Fair',
    poor: 'Poor',
    twoFactorAuth: 'Two-Factor Authentication',
    biometricAuth: 'Biometric Authentication',
    activeSessions: 'Active Sessions',
    securitySettings: 'Security Settings',
    twoFactorAuthDesc: 'Additional authentication with SMS code or app',
    biometricAuthDesc: 'Authentication with fingerprint or face recognition',
    sessionTimeout: 'Session Timeout',
    maxLoginAttempts: 'Max Login Attempts',
    passwordExpiry: 'Password Expiry',
    autoLogout: 'Auto Logout',
    autoLogoutDesc: 'Automatic logout after inactivity',
    securityEvents: 'Security Events',
    successfulLogin: 'Successful Login',
    failedLoginAttempt: 'Failed Login Attempt',
    passwordChanged: 'Password Changed',
    suspiciousActivityDetected: 'Suspicious Activity Detected',
    loginHistory: 'Login History',
    timestamp: 'Timestamp',
    ip: 'IP Address',
    location: 'Location',
    device: 'Device',
    status: 'Status',
    securityRecommendations: 'Security Recommendations',
    enableTwoFactorAuth: 'Enable Two-Factor Authentication',
    enableTwoFactorAuthDesc: 'Recommended to enable two-factor authentication for additional security',
    shortenPasswordExpiry: 'Shorten Password Expiry',
    shortenPasswordExpiryDesc: 'Recommended to shorten password expiry to 30-90 days',
    shortenSessionTimeout: 'Shorten Session Timeout',
    shortenSessionTimeoutDesc: 'Recommended to shorten session timeout to 30 minutes',
    securityInfo: 'Security Information',
    securityDescription: 'Advanced security with professional controls.',
    securityNote1: 'Two-factor authentication',
    securityNote2: 'Suspicious activity monitoring',
    securityNote3: 'Automatic logout',

    // Common
    loading: 'Loading...',
    error: 'Error',
    retry: 'Retry',
    success: 'Success',
    warning: 'Warning',
    info: 'Info',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    confirm: 'Confirm',
    close: 'Close'
  }
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('he') // Hebrew as default
  
  const t = (key) => {
    return translations[language][key] || key
  }
  
  const toggleLanguage = () => {
    setLanguage(prev => prev === 'he' ? 'en' : 'he')
  }
  
  const isRTL = language === 'he'
  
  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage, 
      toggleLanguage, 
      t, 
      isRTL 
    }}>
      {children}
    </LanguageContext.Provider>
  )
}
